name: Release package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install

      - name: Release package
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
